import json, re

path = "/home/claude/gamedb/JRPG_Design_Codex.html"
html = open(path, encoding="utf-8").read()

FF = "Final Fantasy VII Rebirth"
FFX = "Final Fantasy X"
P5 = "Persona 5 Royal"
XC3 = "Xenoblade Chronicles 3"
DQ = "Dragon Quest XI"
TK = "The Legend of Zelda: Tears of the Kingdom"
CE = "Chained Echoes"
SS = "Sea of Stars"

E = "Exploration & Rewards"; P = "Progression & Upgrades"; C = "Combat"
EC = "Economy & Currency"; T = "Traversal"; SC = "Side Content & Minigames"
SR = "Social & Relationships"; M = "Meta & Replayability"

rows = [
# ---------- FF7 Rebirth: the 5 from the deep-dive ----------
(FF,"Chocobo Racing + Chocobo Gear",P,
"Every regional chocobo has base stats (speed, acceleration, cornering, etc.) and an innate race skill. Gear bought with Golden Plumes (earned by repairing chocobo stops and wrangling in the world) is cosmetic while exploring but alters stats and grants race abilities at the Gold Saucer. Winning races unlocks higher grades and exclusive top-tier gear.",
"Explore region \u2192 earn Golden Plumes \u2192 buy and tune mount gear \u2192 win races \u2192 unlock better gear. Your MOUNT becomes an upgradeable, customizable build.",
"Yes",
"The probable \u201cbig one\u201d from your challenge. Exploration currency \u2192 dedicated upgrade shop \u2192 performance payoff, applied to a companion/mount. Template for making non-combat systems as deep as combat builds."),
(FF,"Enemy Skill Materia (blue magic)",C,
"Only one exists, earned via a Combat Simulator challenge. Its 7 enemy skills unlock through Biological Intel: assess N unique enemies in a region, defeat that region's Classified foe, and reach the required materia level. Each level-up also buffs stats; skills cost no MP.",
"Study every monster \u2192 complete the bestiary \u2192 learn enemy powers + stat buffs. Curiosity about creatures converts directly into a growing toolkit.",
"Maybe",
"A \u201clearn from the world\u201d ability system gated by exploration and monster study instead of random drops \u2014 very on-pillar."),
(FF,"Chadley Combat Simulator (VR arena)",M,
"Tiered VR challenge hub: region battles, summon fights, Biological Intel, then endgame Brutal Challenges (full-party gauntlets) and Legendary Bouts (solo trials). No items allowed. Each character's final Legendary Bout rewards the last manuscript needed to MAX their weapon level.",
"Build a party \u2192 clear escalating trials \u2192 exclusive materia, accessories, and the manuscripts that finish your weapon upgrades. Mastery gates max power.",
"",
"Challenge-arena-gates-max-upgrades: you literally cannot finish upgrading without proving skill. Elegant way to make \u201ceverything upgrades\u201d require demonstrated mastery."),
(FF,"Limit Break level system",C,
"Limit gauge fills from taking damage. Levels 2 and 3 aren't selectable \u2014 they must be primed mid-battle via specific Synergy Abilities (or accessories), and Level 3 is the final Folio node gated behind Party Level 9.",
"Fight well \u2192 escalate through synergy \u2192 unleash a bigger ultimate; permanently unlock the ceiling through meta-progression. The signature move is earned twice.",
"",
"A per-battle escalation layered on a permanent unlock gate \u2014 ultimates that feel earned in the moment AND in the long run."),
(FF,"Johnny's Treasure Trove (collection display)",M,
"88 collector's items earned by mastering nearly every system in the game (minigame high scores, simulator clears, race wins, quests) appear as physical trophies, plaques, and figurines displayed in Johnny's renovated seaside hotel. Completing all 88 grants the final piano sheet and the 100% trophy.",
"Do anything well, anywhere \u2192 a trophy physically appears in a diegetic space \u2192 watch the room fill \u2192 one place visualizes your total mastery.",
"Yes",
"The closest structural cousin to the Elden Ring paintings you love: a curated in-world gallery that rewards doing everything. Consider a \u201ctrophy room\u201d that fills as the player explores your world."),

# ---------- Final Fantasy X ----------
(FFX,"Sphere Grid",P,
"Characters don't gain levels; battles award Sphere Levels (moves on a giant shared node board) and enemies drop typed spheres (Power, Mana, Ability, etc.) that activate the nodes you land on. Each character starts in their own board region but can eventually cross into others' paths. Special spheres warp, teleport, or add new nodes to the board.",
"Every fight yields moves + keys \u2192 visibly walk your character across a map of their own growth \u2192 progression is literally a journey you navigate and can redirect.",
"Yes",
"The iconic \u201cprogression is a map\u201d design \u2014 a perfect metaphor for a game about exploration: character growth itself becomes territory to explore, with crossroads and locked gates."),
(FFX,"Celestial Weapons + world challenges",E,
"Each character's ultimate weapon is found in the world, then powered up by a Crest and a Sigil hidden behind exploration and skill challenges (dodging 200 lightning bolts, chocobo racing, butterfly hunts, blitzball prizes). Until upgraded, the weapon is deliberately weak.",
"Find the legend \u2192 chase its two keys through wildly different world challenges \u2192 the strongest weapons exist only for players who engage with the whole world.",
"Maybe",
"Ultimate gear as a scavenger hunt across every system. Caution: FFX's versions are infamously frustrating (lightning dodging) \u2014 keep the structure, tune the challenges."),
(FFX,"Al Bhed Primers (language collectible)",E,
"26 primer volumes scattered across the world each permanently translate one letter of the Al Bhed language. NPC dialogue written in Al Bhed gradually becomes readable as you collect them.",
"Explore \u2192 find a primer \u2192 the world's dialogue literally becomes more comprehensible \u2192 knowledge itself is the loot.",
"Yes",
"One of the purest \u201cknowledge is a reward\u201d designs ever made: collectibles that upgrade your UNDERSTANDING of the world, not your stats. Deeply on-pillar."),
(FFX,"Blitzball (full sub-game with its own RPG)",SC,
"An underwater sports minigame with its own leagues, tournaments, techniques, and player economy: scout and recruit players found across the whole world, level them up, and teach them tech copied from opponents (Techcopy). Prizes include a Celestial key item.",
"Recruit talent while exploring \u2192 build and level a team \u2192 win leagues \u2192 exclusive prizes. A parallel RPG inside the RPG.",
"",
"Scope warning for a solo dev \u2014 this is a whole second game. But the idea of side-content with its OWN progression, recruitment, and skill-learning is the gold standard."),
(FFX,"Monster Arena (capture economy)",EC,
"Buy special Capture weapons, then defeat fiends with them to capture species. Capturing every species in an area or enough of one kind breeds new original superbosses at the arena, and the owner pays out rare items for each milestone.",
"Hunt systematically across every region \u2192 unlock bespoke challenge bosses + rare rewards \u2192 the bestiary becomes a checklist that generates new content.",
"Maybe",
"Completion that CREATES content (new bosses) rather than just ticking boxes \u2014 completionism rewarded with more game, like FF7R's Classified Intel."),
(FFX,"Aeons (summons that grow with you)",P,
"Summoned aeons are persistent party members with their own stats, learnable abilities (taught by spending items), and unique Overdrives. Their stats scale with Yuna's grid progress, and optional temples/quests hide secret aeons.",
"Progress + explore \u2192 your summons grow and multiply \u2192 companions themselves are upgrade projects.",
"",
"Companions-as-upgradeable-systems; secret companions hidden behind optional exploration are a strong pull."),
(FFX,"Overdrive Modes (customizable trigger)",C,
"Each character's limit gauge can be set to charge from different conditions \u2014 taking damage (Stoic), healing allies (Healer), dodging (Evader), winning (Victor), etc. New modes unlock by performing the relevant action enough times.",
"Play your way \u2192 unlock the mode that matches it \u2192 tune your resource engine to your style.",
"",
"Letting players choose HOW a resource charges is cheap to build and deepens expression. The unlock-by-doing loop rewards experimentation."),

# ---------- Persona 5 Royal ----------
(P5,"Confidants (relationships ARE upgrades)",SR,
"Each of 20+ confidants is a full ranked relationship (1\u201310). Every rank grants concrete gameplay abilities: the gun dealer unlocks better customization, the doctor cheaper items, the politician better negotiation, party members gain combat follow-ups, Baton Pass, and evolved personas at max rank.",
"Spend time with someone \u2192 story deepens AND a mechanical ability unlocks \u2192 social play and power growth are the same activity.",
"Yes",
"The definitive answer to making relationships mechanically real: every bond level pays out a named, specific ability. Perfect model if your game has NPCs worth knowing."),
(P5,"Calendar / time economy",M,
"The game runs on a strict daily calendar with limited time slots (day/evening). Every activity \u2014 dungeons, hangouts, jobs, reading, training \u2014 costs a slot, and deadlines force prioritization. Scarcity makes each choice a build decision.",
"Choose how to spend today \u2192 everything advances SOMETHING \u2192 no wasted time, and replay value from the paths not taken.",
"",
"Careful fit: time pressure can conflict with free exploration. But the core insight \u2014 make every activity advance a visible track so no session feels wasted \u2014 is universal."),
(P5,"Social stats gating content",P,
"Five personal stats (Knowledge, Guts, Charm, Proficiency, Kindness) rise through everyday activities and gate content: certain confidants, dialogue options, jobs, and story choices require minimum ranks.",
"Do mundane activities \u2192 the protagonist himself levels up \u2192 previously closed doors (people, places, options) open.",
"Maybe",
"Stats-as-keys applied to the PLAYER CHARACTER's personality \u2014 an upgrade track where the reward is access, not damage."),
(P5,"Persona fusion + compendium",P,
"Collected personas fuse into stronger ones that inherit chosen skills; the compendium permanently records every persona owned so any can be recalled for money. Completing arcana sets and registering everything feeds a collection meta.",
"Catch \u2192 fuse \u2192 record \u2192 recall: experimentation is never punished because the compendium remembers everything.",
"",
"The compendium is the key lesson: a permanent collection record that removes fear of loss makes players WANT to experiment with consumable-feeling resources."),
(P5,"Will Seeds (dungeon exploration collectibles)",E,
"Each palace dungeon hides exactly three Will Seeds in optional rooms off the critical path. Collecting all three in a palace fuses them into a unique accessory with a powerful skill.",
"Poke into every side room \u2192 find 3 of 3 \u2192 they combine into one strong, thematic reward.",
"Maybe",
"Clean dungeon-scale exploration reward: a small fixed count per dungeon (players can always know if they're done) that converts into gear. Easy to implement, satisfying to complete."),
(P5,"Mementos + request board",E,
"A procedurally-shifting side dungeon that deepens as the story progresses, fed by \u201crequests\u201d (mini-quests from a rumor site) that spawn mini-boss targets inside it. Royal adds a resident NPC whose flower-trading economy and stamps upgrade the dungeon's own rewards.",
"Gather rumors in the real world \u2192 hunt targets in the dungeon \u2192 the dungeon itself gains upgraded loot rates via stamps \u2192 even the dungeon has an upgrade track.",
"",
"Note the Royal twist: collecting stamps upgrades THE DUNGEON's yields \u2014 another system-that-levels-up."),
(P5,"Daily activities that upgrade combat",SC,
"Leisure activities have mechanical payoffs: darts improves a party member's Baton Pass rank, the jazz club teaches party members new skills, batting cages raise stats, the gym raises HP/SP, cooking makes recovery items.",
"Relax in the city \u2192 your combat kit measurably improves \u2192 downtime is never mechanically empty.",
"",
"Every minigame answers \u201cwhat does this permanently improve?\u201d \u2014 the FF7R minigame philosophy taken further."),

# ---------- Xenoblade Chronicles 3 ----------
(XC3,"Exploration EXP (discovering places levels you)",E,
"EXP is granted directly for discovering landmarks and secret areas, completing Collectopaedia Cards, and holding rest-spot discussions \u2014 not just combat. Unique monsters grant a 250% EXP bonus.",
"Walk somewhere new \u2192 the whole party levels up \u2192 wandering is literally progression.",
"Yes",
"The most direct implementation of your pillar in any JRPG: discovery IS experience. Trivial to implement, enormous psychological effect."),
(XC3,"Hero Quests (people are unlockables)",E,
"Optional characters (\u201cHeroes\u201d) are found via \u201c?\u201d markers and questlines scattered through the world. Recruiting one adds a 7th party member AND permanently unlocks their entire class for your main cast.",
"Explore \u2192 meet someone with a story \u2192 gain an ally + a whole new playstyle for everyone \u2192 the best treasure is people.",
"Yes",
"Characters-as-exploration-rewards: finding an NPC unlocks a class/skill tree for the party. Doubles as narrative content and combat depth from one authored asset."),
(XC3,"Class inheritance + Ascension Quests",P,
"Party members equip Hero classes and rank them up; ranks unlock that class's skills and arts for cross-class fusion on other builds. Ascension Quests (unlocked at rank 10) raise the cap to 20, unlocking the class's skill and Talent Art for use anywhere.",
"Master a class \u2192 its pieces become permanent LEGO for every other build \u2192 story quests raise the ceiling.",
"",
"Progression whose payoff is build-crafting freedom: mastered content converts into reusable components."),
(XC3,"Traversal skills taught by Heroes",T,
"Field skills \u2014 wall climbing, rope sliding, scree walking, hazard neutralization \u2014 are taught by specific recruited Heroes. Terrain throughout the world is gated by them; containers and paths visibly tease locked routes.",
"Recruit \u2192 the map's locked verbs open \u2192 revisit old regions with new reach.",
"Yes",
"Same metroidvania logic as FF7R's chocobos, but the KEY is a character you befriend. Beautiful fusion of social and traversal systems."),
(XC3,"Collectopaedia Cards",EC,
"Item-collection requests from NPCs: fill a card with materials gathered while exploring, then send it to a colony of your choice for EXP, colony affinity, and rewards \u2014 no walking back required.",
"Gather as you wander \u2192 hand in remotely \u2192 affinity + EXP \u2192 casual pickup habits feed multiple meters.",
"",
"Frictionless fetch-quests: collection happens passively during exploration and pays into the social layer."),
(XC3,"Colony liberation + affinity webs",SR,
"Freeing colonies opens their quests, shops, and services; raising a colony's affinity level (via quests and card sends) unlocks more. An affinity chart visualizes every NPC relationship changing as you help.",
"Liberate \u2192 a whole community becomes content \u2192 helping visibly rewires a web of relationships \u2192 towns themselves level up.",
"Maybe",
"Settlements with their own progression tracks \u2014 the \u201cshop that grows\u201d pattern scaled to whole communities."),
(XC3,"Unique Monsters (named world bosses)",E,
"Named elite monsters with bespoke titles roam fixed spots; defeating one grants bonus EXP (250%), rare drops, and a gravestone that lets you refight it anytime.",
"Spot an ominous name \u2192 risk the fight \u2192 outsized reward + a permanent rematch monument.",
"",
"Landmark encounters that make the map feel authored; the gravestone-rematch is a cheap, elegant replay feature."),

# ---------- Dragon Quest XI ----------
(DQ,"Fun-Size Forge (crafting as a minigame)",EC,
"Crafting is a turn-based minigame: strike zones on a grid with limited focus points, using special hammer techniques to land each zone in its sweet spot. Quality determines +1/+2/+3 gear; Perfectionist's Pearls let you re-forge. Recipes come from books found in the world.",
"Find recipe \u2192 gather \u2192 play a skill minigame \u2192 quality tier reflects YOUR performance \u2192 gear feels made, not dispensed.",
"Yes",
"Crafting where player skill (not RNG) sets item quality. Pairs perfectly with recipe books as exploration loot."),
(DQ,"Recipe books hidden in the world",E,
"Nearly all crafting recipes come from books found in bookshelves, chests, and quest rewards across the world \u2014 each unlocking new forgeable gear.",
"Check every bookshelf \u2192 new recipes \u2192 new gear projects \u2192 libraries and shelves become loot.",
"Maybe",
"Cheap, thematic exploration bait: knowledge items that expand a crafting system (same pattern as FF7R's transmuter chips)."),
(DQ,"Skill panels (character builder grids)",P,
"Each character spends skill points on a hex-grid board split by weapon type and specialty; buying panels reveals adjacent hidden ones, and some are secret until surrounded. Respec is cheap at churches.",
"Earn points \u2192 open your chosen path \u2192 hidden panels reveal as you commit \u2192 the build tree itself has fog-of-war to explore.",
"",
"Small twist worth stealing: hidden nodes that reveal on approach make even a menu feel like territory being uncovered."),
(DQ,"Pep powers (state-based team moves)",C,
"Characters randomly enter a temporary Pepped Up state after enough turns; specific combinations of pepped characters unlock team moves, some required for quests or rare-item farming.",
"Notice who's glowing \u2192 combo their states \u2192 flashy team payoffs \u2192 spontaneous opportunities create tactical spice.",
"",
"A luck-seasoned team-up layer; simpler cousin of FF7R's synergy system."),
(DQ,"Tickington / Tockles (retro world collect-a-thon)",E,
"In the Definitive Edition, invisible spirits (Tockles) hidden across the 3D world unlock quests inside 2D retro recreations of past Dragon Quest games, with pastword rewards flowing back into the main game.",
"Spot a hidden sparkle \u2192 unlock a themed pocket world \u2192 nostalgia quests \u2192 rewards return to the main adventure.",
"",
"Hidden collectibles that unlock entire pocket DUNGEONS \u2014 collectibles gating content, not just items."),
(DQ,"Draconian Quests (self-imposed challenge toggles)",M,
"At the start, players can enable modifiers like stronger monsters, no armor, reduced EXP from weak foes, or shypox embarrassment \u2014 each toggleable off later but not on.",
"Choose your handicaps \u2192 bragging rights and a tuned challenge \u2192 replayability without new content.",
"",
"Near-zero-cost replayability: exposed difficulty toggles as named \u201cquests.\u201d Compare Sea of Stars' relics, which make this collectible."),
(DQ,"Monster mounts (enemies as traversal keys)",T,
"Certain glowing overworld monsters, once defeated, become rideable mounts with unique traversal: flying, wall-climbing, jumping, smashing barriers \u2014 each needed to reach specific treasures in that zone.",
"Beat the right monster \u2192 ride its power \u2192 previously teasing ledges/cracks open \u2192 combat victories convert into traversal.",
"Maybe",
"Enemies as temporary traversal upgrades: merges your combat and exploration loops into one."),

# ---------- Tears of the Kingdom ----------
(TK,"Shrines \u2192 Lights of Blessing economy",E,
"152 shrines dot every layer of the world; each is a bite-size puzzle or trial that pays one Light of Blessing. Four Lights trade for a heart or stamina upgrade at goddess statues \u2014 the player chooses which.",
"See a glowing landmark \u2192 solve a 5-minute puzzle \u2192 bank progress toward a core upgrade YOU allocate \u2192 the world's most visible beacons are its most reliable rewards.",
"Yes",
"The modern benchmark for exploration\u2192upgrade currency: visible from afar, always worthwhile, player-allocated. Your game needs its version of the \u201cglowing beacon that always pays.\u201d"),
(TK,"Korok seeds \u2192 inventory expansion",E,
"~1000 tiny environmental puzzles (odd rock patterns, pinwheels, races) hide Koroks whose seeds are traded to Hestu for weapon/bow/shield inventory slots.",
"Notice something slightly off \u2192 poke it \u2192 a creature pops out \u2192 trade toward carrying capacity \u2192 micro-curiosity is constantly reinforced.",
"Maybe",
"Micro-rewards for NOTICING: trains players that any oddity is worth touching. You don't need 1000 \u2014 even 50 works."),
(TK,"Armor hunting + Great Fairy upgrades",P,
"Armor pieces are found in the world (caves, quests, chests), each with set bonuses; Great Fairies \u2014 themselves unlocked via a questline \u2014 upgrade armor tiers using monster materials, giving every fight and hunt a purpose.",
"Find the outfit \u2192 hunt materials \u2192 upgrade at a discovered NPC \u2192 exploration finds the gear, MORE exploration feeds its growth.",
"",
"Gear whose upgrade fuel is world materials keeps combat and gathering relevant forever; the upgraders being discoverable NPCs is on-pillar."),
(TK,"Caves + Bubbulfrogs (layered cave economy)",E,
"Hundreds of caves each hide exactly one glowing Bubbulfrog; its gems trade with a traveling merchant for exclusive outfits and items. Cave entrances are marked once cleared.",
"Spot a cave \u2192 always find one glowing creature \u2192 dedicated currency \u2192 exclusive shop. A guaranteed prize makes every cave worth entering.",
"",
"The \u201cexactly one per cave\u201d rule creates perfect trust: players always know there's a payoff and when they're done."),
(TK,"Depths + Lightroots (mirrored map knowledge)",E,
"A vast dark underworld mirrors the surface: every Lightroot below sits exactly beneath a surface shrine. Discovering either hints the other's location, and Lightroots illuminate the darkness as fast-travel nodes.",
"Learn one layer \u2192 automatically gain knowledge of the other \u2192 map mastery compounds across dimensions.",
"Maybe",
"Brilliant knowledge-reward: geography itself is a puzzle whose halves inform each other. Steal the principle: let map knowledge in one area unlock certainty elsewhere."),
(TK,"Zonai batteries (energy as upgrade track)",P,
"Zonai devices drain a battery that upgrades permanently: crystallized charges (from mining, sky islands, dispensers) forge extra battery cells, expanding how long your contraptions run.",
"Explore sky and depths \u2192 charge fragments \u2192 permanently bigger battery \u2192 your creative toolset itself has a progression bar.",
"",
"Another \u201cthe system levels up\u201d case: the building/creativity mechanic has its own upgrade economy fed by exploration."),
(TK,"Ability-driven traversal (Ascend/Recall/Ultrahand)",T,
"A tiny set of abilities granted early \u2014 rise through ceilings, rewind object motion, build vehicles \u2014 multiplies traversal options everywhere, making the entire world permeable in ways the player invents.",
"Given verbs, not paths \u2192 players author their own routes \u2192 every cliff or gap is a creative prompt.",
"",
"Opposite philosophy to gated traversal: give powerful verbs early and design terrain as suggestions. Decide which side your game is on \u2014 or gate a few verbs, then open up."),

# ---------- Chained Echoes ----------
(CE,"Reward Board (achievements that pay gear)",E,
"A large board of concrete objectives per region \u2014 find X treasures, defeat unique monsters, complete quests \u2014 where each tile grants real rewards (gear, materials, SP) and completing rows/clusters pays bonuses.",
"Explore and hunt \u2192 tiles flip \u2192 immediate gear payouts + visible board completion \u2192 the whole game's side content is one legible reward surface.",
"Yes",
"High value, low cost for a solo dev: it's an achievements screen that pays real upgrades. Makes 100%-ing each region feel structured and finite. Arguably the single best steal on this list for your scope."),
(CE,"No random encounters + fixed growth (no-grind design)",M,
"All enemies are visible on the field, stat growth is largely fixed via story/SP rather than level grinding, and the game is explicitly balanced so grinding is neither needed nor very possible.",
"Fight when you choose \u2192 power comes from progress and builds, not repetition \u2192 respect for player time becomes the reward.",
"",
"Design stance, not a feature: if exploration is your reward engine, remove grinding as a competing (boring) reward engine."),
(CE,"Overdrive bar (combat tempo management)",C,
"A shared party gauge moves with every action: keep it in the green Overdrive zone for boosted damage and reduced costs, but overheating penalizes you until vented with specific actions. Different skill types push it differently.",
"Read the bar \u2192 sequence actions to surf the sweet spot \u2192 every turn is a tempo decision even in easy fights.",
"",
"One clever shared gauge gives every battle a rhythm mini-puzzle \u2014 cheap depth for a small team."),
(CE,"Crystal socketing + upgrades that add slots",P,
"Weapons and armor upgrade twice (+/++), each upgrade adding stat boosts AND a crystal slot; crystals grant passive skills, come in sizes, and can be refined smaller/stronger to fit more per item.",
"Upgrade gear \u2192 more sockets \u2192 refine and slot crystals \u2192 equipment is a growing container for a build you compose.",
"Maybe",
"A compact materia-like system a solo dev actually shipped: upgrades that expand CAPACITY (slots) are felt more than raw stats."),
(CE,"Sky Armor (mechs as traversal + second combat layer)",T,
"Mid-game, each character gains a flying mech: fast overworld traversal, access to new areas, and a distinct mech combat mode with its own gear-stance system and Skill RAM upgrade items bought or found in the world.",
"Earn the mech \u2192 the world opens vertically and old zones shrink \u2192 a second, upgradeable combat system arrives with it.",
"",
"One system that simultaneously refreshes traversal, combat, AND the upgrade economy at the midpoint \u2014 great pacing lesson."),
(CE,"Vendor Deals board (targeted hunting shop)",EC,
"A merchant's deal board lists the game's strongest gear, each unlocked by bringing specific rare items \u2014 and each deal tells you exactly where and from what enemy to get them.",
"Read the want-list \u2192 hunt with clear direction \u2192 top-tier gear \u2192 shopping becomes questing with built-in guidance.",
"Maybe",
"Turns a shop into a quest-giver with transparent objectives \u2014 zero quest-scripting cost, strong pull into the world."),
(CE,"Unique monster hunts + guild payoff",E,
"Named unique monsters hide across every region, tracked on the Reward Board; defeating all of them earns a special reward from the guild leader tied to ultimate equipment.",
"Spot the special enemy \u2192 win \u2192 board tile + progress toward a grand completion prize \u2192 hunting has both immediate and capstone payoffs.",
"",
"Local reward + global capstone from the same hunts (the protorelic pattern, indie-sized)."),

# ---------- Sea of Stars ----------
(SS,"Locks (telegraphed attack-break puzzles)",C,
"When an enemy charges a big attack, icons show a sequence of damage types; hitting the enemy with matching types before the timer breaks the \u201clocks,\u201d weakening or canceling the attack.",
"Read the icons \u2192 solve the type puzzle with your party's kit \u2192 prevent the blow \u2192 every enemy cast is a micro-puzzle with visible stakes.",
"Maybe",
"Turn-based combat where defense is an interactive puzzle, not a stat check. Cheap to implement, huge engagement return."),
(SS,"Timed hits + Live Mana",C,
"Pressing attack at the moment of impact deals bonus damage and feeds resources; timing blocks reduces incoming damage. Attacks also leave Live Mana orbs on the field that any character can absorb to empower their next move.",
"Stay present every turn \u2192 rhythm skill converts to damage and resources \u2192 turn-based combat feels hands-on.",
"",
"The Mario RPG lineage: timing keeps players engaged during every animation. Low-cost, high-feel."),
(SS,"Relics (difficulty as collectible items)",M,
"Difficulty modifiers are physical relics bought or found in the world \u2014 from Amulet of Storytelling (near-auto-win for story-focused players) to Artful Gambit (a brutal 95% HP cut with its own achievement) \u2014 toggleable anytime in the menu.",
"Find/buy a relic \u2192 own your difficulty settings as in-world objects \u2192 accessibility and challenge both become collectibles rather than menu shame.",
"Yes",
"Genius reframe: difficulty options as explorable LOOT. Players who want ease or pain both get rewarded paths. Trivial to build, memorable to players."),
(SS,"Rainbow Conches \u2192 tiered trade-in",E,
"60 conches hide across every area (none missable); handing them to a collector NPC pays out escalating reward tiers, and the full set grants the Rainbow Star, a requirement for the true ending.",
"Peek everywhere \u2192 conch \u2192 tiered prizes at the collector \u2192 the complete set gates the TRUE ENDING \u2192 thorough explorers get the real story.",
"Maybe",
"Bold move: the best ending is an exploration reward. Decide if your game dares tie narrative payoff to world mastery."),
(SS,"Mirth (build a town from found plans)",E,
"Building plans found through exploration and conch rewards construct facilities in your own town \u2014 an inn, shops, a fishing hut \u2014 and some need specific NPCs discovered elsewhere recruited to staff them.",
"Find plans + people \u2192 your home base physically grows \u2192 each building unlocks services and relics \u2192 exploration builds a place that's YOURS.",
"Yes",
"A base that grows from exploration loot is a powerful visible progress monument \u2014 the town is a trophy room you live in (compare Johnny's Trove)."),
(SS,"Falcon-Eyed Parrot (earned completion tracker)",M,
"A relic earned via conch trade-ins adds a parrot to the world map that reports which collectibles remain on any selected island and where.",
"Invest in exploration \u2192 unlock a tool that makes finishing exploration pleasant \u2192 completionists are given respect, not wikis.",
"Yes",
"Ship your own \u201cwhere's the last one?\u201d tool as an EARNED upgrade \u2014 preempts guide-dependence and rewards commitment. Very cheap to build."),
(SS,"Solstice Shrines + day/night as a verb",E,
"The heroes can turn the sun and moon at will; puzzles and hidden shrines use time-of-day angles (light beams, shadows, tides) as their core mechanic, with shrine completion feeding endgame content.",
"Use your unique power on the world itself \u2192 environments reconfigure \u2192 secrets tied to your identity as solstice warriors.",
"",
"Give the player one world-manipulation verb and build secrets around it \u2014 identity, puzzle design, and exploration in one mechanic."),
]

# Build JS entries
def js(s):
    return json.dumps(s, ensure_ascii=False)

entries = []
n = 32
for game, name, cat, how, loop, want, notes in rows:
    entries.append(
        '{id:"M%03d",game:%s,name:%s,cat:%s,\nhow:%s,\nloop:%s,\nrating:0,want:%s,\nnotes:%s}'
        % (n, js(game), js(name), js(cat), js(how), js(loop), js(want), js(notes))
    )
    n += 1

block = ",\n" + ",\n".join(entries) + "\n];"

anchor = 'rating:0,want:"",notes:""}\n];'
assert html.count(anchor) == 1, "anchor not found"
html = html.replace(anchor, 'rating:0,want:"",notes:""}' + block)

# Mark roster games as researched
for g in ['"Final Fantasy X"','"Persona 5 Royal"','"Xenoblade Chronicles 3"','"Dragon Quest XI"',
          '"The Legend of Zelda: Tears of the Kingdom"','"Chained Echoes"','"Sea of Stars"']:
    pass
html = html.replace('status:"To Research"','status:"Researched"')
html = html.replace('status:"Researching"','status:"Researched"')

open(path, "w", encoding="utf-8").write(html)
print("patched, total mechanics:", html.count('id:"M0') + html.count('id:"M1') if False else n-1)
